### ISSUE TITLE
In The DeltaTimer App, on exit it crashes

### ISSUE THREAD

**Issue by anantham** [anantham/Delta#1]
there is a separate thread keeps running which updates the timer even if the main activity is not in its visible state.This thread is abruptly brought to a close? when we exit the application using the "back" button when the timer is running, (whatever the reason) the app crashes immediately.

**Comment by vishnugt** [comment]
Just add these code lines in the reset function, this will stop all currently active threads excluding the main/UI thread. 

```
Thread[] threads = new Thread[Thread.activeCount()];
            Thread.enumerate(threads);
            for (Thread t : threads) 
            {
                t.interrupt();
            }
```

**Comment by anantham** [comment]
Thanks Vishnu, you are right, that will work.
I also found another method, as we need to top thread when we exit the app, we can --

//to stop the crashing which occurs when we exit the app using the back key while the timer is running
//i override the ondestroy which is called when the back button is clicked and stop the thread which //updates the time and itself
    @Override
    protected void onDestroy() {
        //first we need to  call up to the superclass
        super.onDestroy();
                // basically removes all pending posts of "updateTimer" in the message queue
        //ie stops the updating to the textview, (currenttime)
        handler.removeCallbacks(updateTimer);
    }

**Comment by anantham** [comment]
I should have closed it then itself.
Well issue resolved. Nothing to see here guys. :)
